name: glam_rider_app
description: GLAM Rider Onboarding App — Delivery Partner Portal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.1
  http: ^1.2.1
  google_fonts: ^6.2.1
  geolocator: ^13.0.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
